version: '3.8'
services:
  postgres:
    container_name: parttimedev_postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass123

  # Comment out api section to use the database for local development
  api:
    container_name: parttimedev_api_dev
    image: leolazz/parttimedev-backend:2.0
    environment:
      - DATABASE_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - DATABASE_NAME=parttimedev
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
    command: npm run start:prod
    ports:
      - 8080:8080
      # debugger port
      - 9229:9229
    restart: unless-stopped
