version: '3.8'
services:
  db:
    container_name: parttimedev_postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - docker.env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - docker.env
    ports:
      - '5050:80'
  api:
    container_name: parttimedev_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: npm run start:debug
    ports:
      - 8080:8080
      # debugger port
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
