apiVersion: apps/v1
kind: Deployment
metadata:
  name: parttimedev-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parttimedev-backend
  template:
    metadata:
      labels:
        app: parttimedev-backend
    spec:
      containers:
        - name: parttimedev-backend
          image: leolazz/parttimedev-backend:v1.2
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB-host
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: parttimedev-backend-service
spec:
  type: NodePort
  selector:
    app: parttimedev-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
